### ISSUE TITLE
Start project

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#1]
Hi Shramee,

We want to start a new free page customizer that works on every theme.

We will also then create a 'pro' version to sell.

The free version will need to work on every theme that has good standards and will hide page and post titles...

For research see this theme: https://wordpress.org/plugins/hide-title/

Can we also start with this boilderplate: 

https://github.com/mattyza/starter-plugin/

I will add more tickets as we go...

**Comment by nickburne** [comment]
Hold on this for now. Decided not to start this yet.

**Comment by nickburne** [comment]
Ok - so this is back on... please go ahead.

**Comment by shramee** [comment]
Yeah we can start with this, Its got a lot of stuff in-built will need some time to explore it. How about starting with store front boilerplate ( might sound funny but since I'm used to it, it will take less time. ) ?

**Comment by nickburne** [comment]
Sounds fine...

**Comment by shramee** [comment]
Cool, lets get started then ; )

**Comment by nickburne** [comment]
Let me know when I can close this ticket...

**Comment by shramee** [comment]
This is done, sorry I didn't comment yesterday. Will work on options now.

**Comment by nickburne** [comment]
Ok - however it doesn't look like all the files from the boilerplate are here?

**Comment by shramee** [comment]
Hmm... I got only ones I thought We'd need I removed some stuff, codekit, sold on woo commerce stuff and woo functions.

**Comment by nickburne** [comment]
ok... closing..
