### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#10]
We want this plugin to work on all custom post types...

Not just pages and products, but any custom post type. 

In Canvas Page Builder (and SiteOrigin Page Builder) it detects the post types (see pic below)

![screenshot 2015-04-06 11 59 18](https://cloud.githubusercontent.com/assets/3784875/7003567/71f6fbac-dc54-11e4-9026-f3bce95db3d7.png)

**Comment by nickburne** [comment]
I am concerned that if we make the options available on any post type we will run into lots of support issues where the options don't work for those post types...

Maybe the best way to test this is for you to make all the options work on ALL post types and then I will test it on some sites...

What do you think @shramee ?

**Comment by nickburne** [comment]
By the way, this is a major feature of the pro version of this plugin. It is is the top idea on our ideas board: 

https://pootlepress.uservoice.com/forums/238444-canvas-extension-ideas/filters/top

**Comment by shramee** [comment]
Yeah, good.

**Comment by shramee** [comment]
Making meta box stuff work on all post types.

**Comment by nickburne** [comment]
ok - let me know when done...

**Comment by shramee** [comment]
Okay

**Comment by shramee** [comment]
Done, Kindly check this out.

**Comment by shramee** [comment]
I just copied a piece of code from sfx-page-cuastomizer which cause some errors to show up on enabling wp_debug, so corrected that in commit d76bb7d808d34b49e0076dc7254d593313ba2766

**Comment by shramee** [comment]
Tabs displayed with weird styles in products.

**Comment by nickburne** [comment]
Ok - checking this out now...

**Comment by nickburne** [comment]
Ok - this seems to work really well for normal custom post types! Well done. I suggest we leave this here and then pick up further issues in support!
