### ISSUE TITLE
Options for all themes

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#2]
Can we add the following options that would work on ALL wordpress themes?

Page background image
Page background color
Hide header
Header background image
Header background color
Hide footer

So same as Storefront Page Customizer but would work with all well developed WordPress themes...

**Comment by shramee** [comment]
Page background image - Yep
Page background color - Yep
Hide header - Guessing the element that could be a header.
Header background image - Guessing the element that could be a header.
Header background color - Guessing the element that could be a header.
Hide footer - Guessing the element that could be a footer.

**Comment by nickburne** [comment]
What do you mean 'Guessing the element that could be...'

Is this because different themes have different CSS?

**Comment by shramee** [comment]
Right, for instance most themes would use <header> tag  for header, while other might use <div> with class header or site-header or main-header or...

**Comment by nickburne** [comment]
Just so you know we will develop a full 'PRO' version of this and then also do a free version from the PRO version later (just like we will do from Blog widget)

**Comment by shramee** [comment]
??

**Comment by nickburne** [comment]
So is it possible to do it so that it works with 'most' themes (so we guess at more than one header)

?

**Comment by shramee** [comment]
<blockquote>Right, for instance most themes would use <b> &lt;header&gt; </b> tag for header, while other might use <b> &lt;div&gt; </b> with class header or site-header or main-header or...</blockquote>

**Comment by shramee** [comment]
I forgot to use &amp;lt; instead of &lt; so, Yeah we can use the simple selectors with popular classes and use !important.

**Comment by nickburne** [comment]
Ok - sounds good. Let's get these options done and then I will test on 4 to 5 themes at random...

Thanks!

N

**Comment by shramee** [comment]
Cool, this should be fun!!!

**Comment by nickburne** [comment]
: )

**Comment by shramee** [comment]
Classes/ID used:
Header:  #masthead, #header, #site-header, .site-header
Body:    body
Footer:  #footer, #site-footer, .site-footer
Tested on Storefront, Canvas and TwentyThirteen

**Comment by shramee** [comment]
Kindly check this out.

**Comment by nickburne** [comment]
Will do - exciting!

**Comment by nickburne** [comment]
Working well.

Hide header didn't work on a theme call: Customizr

**Comment by shramee** [comment]
Okay let's check it out.

**Comment by shramee** [comment]
Sorry closed it by mistake...
Kindly check this out.

**Comment by nickburne** [comment]
Yep - that works. 

As we test more themes we can add to the variables for each element.

For now I will close this and add other tickets when we find issues.

Well done!
