### ISSUE TITLE
Add option to hide breadcrumbs...

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#3]
Good luck!

**Comment by nickburne** [comment]
again - probably many ways sites do this... Start with storefront. Also check out Customizr

**Comment by shramee** [comment]
CSS selectors used : 
#breadcrumbs, #breadcrumb, .breadcrumbs, .breadcrumb, .breadcrumbs-trail, .wc-breadcrumbs, .wc-breadcrumb, .woocommerce-breadcrumb, .woocommerce-breadcrumbs

**Comment by nickburne** [comment]
Well done!
