### ISSUE TITLE
Keeping settings between themes

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#5]
I know this is going to be hard, but it has to keep settings between theme changes. 

I changed from TwentyFifteen to Customizr and the test page I had put a background image into lost it's background image...

Can you see if you can fix it?

Thanks!

N

**Comment by shramee** [comment]
We are storing stuff with Post Meta it is independent of the theme, <b>only styles application could be an issue</b>, but if we are talking about body background this shouldn't be a problem since styles are being applied directly to the body, this shouldn't happen.

**Comment by nickburne** [comment]
It would be great if all the same settings were kept.

What do you mean 'only styles application could be an issue' - please explain so I can understand!

: )

Thanks,

Nick

**Comment by shramee** [comment]
I was talking about how our theme applies the styles for instance our plugin applies header styles to #header also now there could be an theme which would use this id for loop header, so only the way styles work can be changed by the theme.

**Comment by nickburne** [comment]
Ok - so if I change from one theme to another and they have a difference in the way they style a header, my setting will not persist. Is that correct?

Can we make it persist?

**Comment by shramee** [comment]
Yep, we will need to check if the property works on that theme if it does it will work on theme change.

**Comment by shramee** [comment]
For instance header setting works on Customizr and Twenty Fifteen, no matter whether we switch from 2015 to customizr or from customizr to 2015, fortunately ; ) , settings will persist.

**Comment by nickburne** [comment]
Makes sense. This should always be our aim. So I will close this ticket now you are clear how I want this to work... ; )
