### ISSUE TITLE
Header background image not working in Customizr theme

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#6]
Please fix for this theme and all future themes that use the same code... ; )

**Comment by shramee** [comment]
Just to confirm we are talking about greenish theme in the picture below right?
![customizer](https://cloud.githubusercontent.com/assets/11048263/6985163/ebe238f4-da4d-11e4-8e98-197730080bd2.png)

**Comment by shramee** [comment]
I'm able to put a header image on it, maybe that's because of new commits. Let me know if this is still an issue.

**Comment by nickburne** [comment]
It's working now! Closed ; )
