### ISSUE TITLE
Add more options when users adds a background image per page

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#7]
Start with the same as storefront... but to work on every theme...

Background Repeat
  No Repeat
  Tile
  Tile Horizontally
  Tile Vertically

Background Position
  Left
  Center
  Right

Background Attachment
  Scroll
  Fixed

**Comment by shramee** [comment]
This is done too.

**Comment by nickburne** [comment]
Awesome....

**Comment by nickburne** [comment]
It would be good if the options could be hidden until the user puts in a background image (like you did in Storefront Page Customizer)

Is that cool?

**Comment by shramee** [comment]
Hmmm... Okay let me see.

**Comment by shramee** [comment]
Hides for me until I select an image.

**Comment by shramee** [comment]
(Actually I used the same code I did in Storefront)

**Comment by nickburne** [comment]
Ok - it works nice now. Probably cache. Closed!
