### ISSUE TITLE
Create tabs like Yoast SEO plugin

### ISSUE THREAD

**Issue by nickburne** [PootlePress/page-customizer#8]
![screenshot 2015-04-03 18 06 45](https://cloud.githubusercontent.com/assets/3784875/6985525/56ccd7c2-da2c-11e4-9ca0-d3ec934593d5.png)

**Comment by nickburne** [comment]
How would you break up the options for each tab @shramee ?

**Comment by nickburne** [comment]
I would like to hear your thoughts....

**Comment by shramee** [comment]
Well...
We could have 'em as different sections in the page like Body, Header, Content, Footer. Or may be like Toggle Hide/show, Aesthetics, Typography, Will depend on which more options we plan to have.

**Comment by shramee** [comment]
Whaddya say?

**Comment by nickburne** [comment]
Yeah - I think the first one.

Start with:
- General
- Background
- Header

**Comment by nickburne** [comment]
Actually - start with

Background
Header
Content
Footer

**Comment by shramee** [comment]
Cool

**Comment by nickburne** [comment]
Super sweet work @Shramee

Closing this. thanks for all your great work... See you Monday

**Comment by shramee** [comment]
Thanks, tc
